CREATE TABLE Paciente (codpac SERIAL NOT NULL, nompac varchar(120) NOT NULL, datpac date NOT NULL, pespac int4 NOT NULL, altpac int4 NOT NULL, cpfpac int4 NOT NULL, sexpac varchar(1) NOT NULL CHECK(sexpac in ('F','M')), codusu int4 NOT NULL, codsin int4 NOT NULL, PRIMARY KEY (codpac));
COMMENT ON TABLE Paciente IS 'Tabela de pacientes';
COMMENT ON COLUMN Paciente.nompac IS 'Nome do paciente.';
COMMENT ON COLUMN Paciente.datpac IS 'Data de nascimento do paciente.';
COMMENT ON COLUMN Paciente.pespac IS 'Peso do Paciente';
COMMENT ON COLUMN Paciente.altpac IS 'Altura do Paciente';
COMMENT ON COLUMN Paciente.cpfpac IS 'CPF do paciente.';
COMMENT ON COLUMN Paciente.sexpac IS 'Sexo do paciente , F=Feminino , M=Masculino';
COMMENT ON COLUMN Paciente.codusu IS 'Código do usuario';
CREATE TABLE Sintoma (codsin SERIAL NOT NULL, covsin varchar(1) NOT NULL CHECK(covsin in ('S','N')), sitsin varchar(250) NOT NULL, intsin numeric(1, 3) NOT NULL, PRIMARY KEY (codsin));
COMMENT ON TABLE Sintoma IS 'Tabela de sintomas do corona virus';
COMMENT ON COLUMN Sintoma.codsin IS 'codigo sintoma';
COMMENT ON COLUMN Sintoma.covsin IS 'positivo para covid, S=sim ,N=nao';
COMMENT ON COLUMN Sintoma.sitsin IS 'Sintomas';
COMMENT ON COLUMN Sintoma.intsin IS 'Intensidade sintoma 1=fraco,2=médio, 3=forte';
CREATE TABLE Medico (codmed SERIAL NOT NULL, nommed varchar(120) NOT NULL, datmed date NOT NULL, crmmed int4 NOT NULL, PRIMARY KEY (codmed));
COMMENT ON TABLE Medico IS 'Tabela de Médicos';
COMMENT ON COLUMN Medico.codmed IS 'Código do médico.';
COMMENT ON COLUMN Medico.nommed IS 'Nome do médico.';
COMMENT ON COLUMN Medico.datmed IS 'Data de nascimento do médico.';
COMMENT ON COLUMN Medico.crmmed IS 'Número de CRM(Conselho Regional de Medicina) do médico.';
CREATE TABLE Usuario (codusu SERIAL NOT NULL, nomusu varchar(30) NOT NULL, cpfusu int4 NOT NULL, codhosp int4 NOT NULL, PRIMARY KEY (codusu));
COMMENT ON TABLE Usuario IS 'Tabela de Usuarios';
COMMENT ON COLUMN Usuario.codusu IS 'Código do usuário.';
COMMENT ON COLUMN Usuario.nomusu IS 'Nome do usuário.';
COMMENT ON COLUMN Usuario.cpfusu IS 'CPF do Usuário';
COMMENT ON COLUMN Usuario.codhosp IS 'Código do Hospital';
CREATE TABLE Hospital (codhos SERIAL NOT NULL, nomhos varchar(120) NOT NULL, quahos int4 NOT NULL, PRIMARY KEY (codhos));
COMMENT ON TABLE Hospital IS 'Tabela de Hospitais';
COMMENT ON COLUMN Hospital.codhos IS 'Código do hospital.';
COMMENT ON COLUMN Hospital.nomhos IS 'Nome do hospital.';
COMMENT ON COLUMN Hospital.quahos IS 'Quantidade de internados.';
CREATE TABLE Endereco (codend SERIAL NOT NULL, ruaend varchar(100) NOT NULL, numend int4 NOT NULL, cidend varchar(120) NOT NULL, cepend int4 NOT NULL, baiend varchar(120) NOT NULL, codpac int4 NOT NULL, codmed int4 NOT NULL, PRIMARY KEY (codend));
COMMENT ON TABLE Endereco IS 'Tabela de endereço';
COMMENT ON COLUMN Endereco.codend IS 'Código do endereço';
COMMENT ON COLUMN Endereco.ruaend IS 'Rua do hopital.';
COMMENT ON COLUMN Endereco.numend IS 'Número do hospital.';
COMMENT ON COLUMN Endereco.cidend IS 'Cidade onde a entidade se localiza.';
COMMENT ON COLUMN Endereco.cepend IS 'CEP  da entidade.';
COMMENT ON COLUMN Endereco.baiend IS 'Bairro do endreeço.';
CREATE TABLE Agendamento (codage SERIAL NOT NULL, horage timestamp(4) NOT NULL, datage date NOT NULL, codmed int4 NOT NULL, codhos int4 NOT NULL, PRIMARY KEY (codage));
COMMENT ON TABLE Agendamento IS 'Tabela de agendamento';
COMMENT ON COLUMN Agendamento.codage IS 'Código do agendamento.';
COMMENT ON COLUMN Agendamento.horage IS 'Horáro do agendamento.';
COMMENT ON COLUMN Agendamento.datage IS 'Data do agendamento.';
COMMENT ON COLUMN Agendamento.codmed IS 'Código do médico';
COMMENT ON COLUMN Agendamento.codhos IS 'Código do Hospital';
CREATE TABLE Consulta (codcon SERIAL NOT NULL, sitpac varchar(1) NOT NULL CHECK(sitpac in ('S','P','N','R')), datcons date NOT NULL, codpac int4 NOT NULL, PRIMARY KEY (codcon));
COMMENT ON COLUMN Consulta.codcon IS 'Código da consulta';
COMMENT ON COLUMN Consulta.sitpac IS 'Situação do Paciente ,   S = Suspeito,P = Positivo,N = Negativo,R =Recuperado';
COMMENT ON COLUMN Consulta.datcons IS 'Data da consulta';
CREATE TABLE Paciente_Agendamento (codpac int4 NOT NULL, codage int4 NOT NULL, codusu int4 NOT NULL, PRIMARY KEY (codpac, codage, codusu));
ALTER TABLE Endereco ADD CONSTRAINT FKEndereco697270 FOREIGN KEY (codpac) REFERENCES Paciente (codpac);
ALTER TABLE Paciente ADD CONSTRAINT FKPaciente551311 FOREIGN KEY (codusu) REFERENCES Usuario (codusu);
ALTER TABLE Agendamento ADD CONSTRAINT FKAgendament28796 FOREIGN KEY (codmed) REFERENCES Medico (codmed);
ALTER TABLE Usuario ADD CONSTRAINT FKUsuario684551 FOREIGN KEY (codhosp) REFERENCES Hospital (codhos);
ALTER TABLE Agendamento ADD CONSTRAINT FKAgendament770750 FOREIGN KEY (codhos) REFERENCES Hospital (codhos);
ALTER TABLE Endereco ADD CONSTRAINT FKEndereco311012 FOREIGN KEY (codmed) REFERENCES Medico (codmed);
ALTER TABLE Consulta ADD CONSTRAINT FKConsulta472449 FOREIGN KEY (codpac) REFERENCES Paciente (codpac);
ALTER TABLE Paciente_Agendamento ADD CONSTRAINT FKPaciente_A507221 FOREIGN KEY (codpac) REFERENCES Paciente (codpac);
ALTER TABLE Paciente_Agendamento ADD CONSTRAINT FKPaciente_A892113 FOREIGN KEY (codage) REFERENCES Agendamento (codage);
ALTER TABLE Paciente ADD CONSTRAINT FKPaciente213471 FOREIGN KEY (codsin) REFERENCES Sintoma (codsin);
